/**
 * Database Schema - Auto-generated from CockroachDB
 *
 * This file re-exports the auto-generated schema from drizzle-kit pull.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten.
 *
 * To update the schema:
 * 1. Make changes directly in CockroachDB
 * 2. Run: npx drizzle-kit pull
 *
 * The actual schema definitions are in: src/lib/db/generated/schema.ts
 * Generated by: drizzle-kit pull
 */

// Re-export everything from the generated schema
export * from "./generated/schema";

// Re-export relations
export * from "./generated/relations";
