-- Questions table already exists in the database
-- This migration is a no-op since the questions table
-- is already present in the database with the correct schema
--
-- The existing questions table has the following structure:
-- - id: uuid PRIMARY KEY
-- - question: text NOT NULL
-- - tournament: text NOT NULL
-- - division: text NOT NULL
-- - options: jsonb DEFAULT '[]'
-- - answers: jsonb NOT NULL
-- - subtopics: jsonb DEFAULT '[]'
-- - difficulty: numeric DEFAULT '0.5'
-- - event: text NOT NULL
-- - created_at: timestamp DEFAULT now()
-- - updated_at: timestamp DEFAULT now()
--
-- No changes needed - schema is already correct
