export const SCIENCE_OLYMPIAD_EVENTS = [
  "Anatomy - Skeletal",
  "Anatomy - Muscular",
  "Anatomy - Integumentary",
  "Anatomy - Cardiovascular",
  "Anatomy - Lymphatic",
  "Anatomy - Excretory",
  "Anatomy - Respiratory",
  "Anatomy - Digestive",
  "Anatomy - Immune",
  "Anatomy - Nervous",
  "Anatomy - Sense Organs",
  "Anatomy - Endocrine",
  "Astronomy",
  "Botany",
  "Cell Biology",
  "Chemistry Lab",
  "Circuit Lab",
  "Codebusters",
  "Designer Genes",
  "Detector Building",
  "Disease Detectives",
  "Dynamic Planet - Glaciers",
  "Dynamic Planet - Earthquakes, Volcanoes, and Tectonics",
  "Dynamic Planet - Earth's Fresh Waters",
  "Dynamic Planet - Oceanography",
  "Dynamic Planet - Tectonics",
  "Ecology",
  "Entomology",
  "Environmental Chemistry",
  "Fermi Questions",
  "Forensics",
  "Forestry",
  "Fossils",
  "Geologic Mapping",
  "Gravity Vehicle",
  "Green Generation",
  "Helicopter",
  "Heredity",
  "Herpetology",
  "Hovercraft",
  "Invasive Species",
  "It's About Time",
  "Machines",
  "Materials Science - Ceramics",
  "Materials Science - Polymers and Plastics",
  "Materials Science - General",
  "Microbe Mission",
  "Mission Possible",
  "Meteorology",
  "Metric Mastery",
  "Mousetrap Vehicle",
  "Optics",
  "Ornithology",
  "Physics Lab",
  "Rocks and Minerals",
  "Reach for the Stars",
  "Solar System",
  "Sounds of Music",
  "Thermodynamics",
  "Water Quality - Freshwater",
  "Water Quality - Marine/Estuaries",
  "Water Quality - Freshwater/Estuaries",
  "Wind Power",
  "Potions and Poisons",
  "Crave the Wave",
  "Food Science",
];
