import type {
	AssignmentQuestionRecord,
	AssignmentRecord,
	AssignmentRosterRecord,
	AssignmentSubmissionRecord,
	TeamActiveTimerRecord,
	TeamEventAttendeeRecord,
	TeamEventRecord,
	TeamGroupRecord,
	TeamInvitationRecord,
	TeamMembershipRecord,
	TeamNotificationRecord,
	TeamRosterRecord,
	TeamStreamPostRecord,
	TeamUnitRecord,
	TestUser,
} from "./types";

export const mockDb = {
	users: new Map<string, TestUser>(),
	teamGroups: new Map<string, TeamGroupRecord>(),
	teamUnits: new Map<string, TeamUnitRecord>(),
	memberships: new Map<string, TeamMembershipRecord>(),
	rosterEntries: new Map<string, TeamRosterRecord>(),
	streamPosts: new Map<string, TeamStreamPostRecord>(),
	events: new Map<string, TeamEventRecord>(),
	eventAttendees: new Map<string, TeamEventAttendeeRecord>(),
	assignments: new Map<string, AssignmentRecord>(),
	assignmentQuestions: new Map<string, AssignmentQuestionRecord>(),
	assignmentRoster: new Map<string, AssignmentRosterRecord>(),
	assignmentSubmissions: new Map<string, AssignmentSubmissionRecord>(),
	teamInvitations: new Map<string, TeamInvitationRecord>(),
	teamNotifications: new Map<string, TeamNotificationRecord>(),
	activeTimers: new Map<string, TeamActiveTimerRecord>(),
};
